package org.cef.misc;

public enum CefCursorType {
	POINTER(0),
	CROSS(0x36003), // GLFW_CROSSHAIR_CURSOR
	HAND(0x36004), // GLFW_HAND_CURSOR
	IBEAM(0x36002), // GLFW_IBEAM_CURSOR
	WAIT(0),
	HELP(0),
	EAST_RESIZE(0x36005), // GLFW_RESIZE_EW_CURSOR
	NORTH_RESIZE(0x36006), // GLFW_RESIZE_NS_CURSOR
	NORTH_EAST_RESIZE(0x36008), // GLFW_RESIZE_NESW_CURSOR
	NORTH_WEST_RESIZE(0x36007), // GLFW_RESIZE_NWSE_CURSOR
	SOUTH_RESIZE(0x36006), // GLFW_RESIZE_NS_CURSOR
	SOUTH_EAST_RESIZE(0x36007), // GLFW_RESIZE_NWSE_CURSOR
	SOUTH_WEST_RESIZE(0x36008), // GLFW_RESIZE_NESW_CURSOR
	WEST_RESIZE(0x36005), // GLFW_RESIZE_EW_CURSOR
	NORTH_SOUTH_RESIZE(0x36006), // GLFW_RESIZE_NS_CURSOR
	EAST_WEST_RESIZE(0x36005), // GLFW_RESIZE_EW_CURSOR
	NORTH_EAST_SOUTH_WEST_RESIZE(0x36008), // GLFW_RESIZE_NESW_CURSOR
	NORTH_WEST_SOUTH_EAST_RESIZE(0x36007), // GLFW_RESIZE_NWSE_CURSOR
	COLUMN_RESIZE(0),
	ROW_RESIZE(0),
	MIDDLE_PANNING(0),
	EAST_PANNING(0),
	NORTH_PANNING(0),
	NORTH_EAST_PANNING(0),
	NORTH_WEST_PANNING(0),
	SOUTH_PANNING(0),
	SOUTH_EAST_PANNING(0),
	SOUTH_WEST_PANNING(0),
	WEST_PANNING(0),
	MOVE(0x36009), // GLFW_RESIZE_ALL_CURSOR
	VERTICAL_IBEAM(0), // VERTICAL_TEXT
	CELL(0),
	CONTEXT_MENU(0),
	ALIAS(0),
	PROGRESS(0),
	NO_DROP(0x3600A), // GLFW_NOT_ALLOWED_CURSOR
	COPY(0),
	NONE(0),
	NOT_ALLOWED(0x3600A), // GLFW_NOT_ALLOWED_CURSOR
	ZOOM_IN(0),
	ZOOM_OUT(0),
	GRAB(0),
	GRABBING(0),
	CUSTOM(0),
	;
	
	public final int glfwId;
	
	CefCursorType(int glfwId) {
		this.glfwId = glfwId;
	}
	
	public static CefCursorType fromId(int id) {
		return values()[id];
	}
}
