/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_handler_CefClientHandler */

#ifndef _Included_org_cef_handler_CefClientHandler
#define _Included_org_cef_handler_CefClientHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_handler_CefClientHandler
 * Method:    N_CefClientHandler_CTOR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_handler_CefClientHandler_N_1CefClientHandler_1CTOR
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_handler_CefClientHandler
 * Method:    N_removeDialogHandler
 * Signature: (Lorg/cef/handler/CefDialogHandler;)V
 */
JNIEXPORT void JNICALL Java_org_cef_handler_CefClientHandler_N_1removeDialogHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_handler_CefClientHandler
 * Method:    N_removeDisplayHandler
 * Signature: (Lorg/cef/handler/CefDisplayHandler;)V
 */
JNIEXPORT void JNICALL Java_org_cef_handler_CefClientHandler_N_1removeDisplayHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_handler_CefClientHandler
 * Method:    N_removeFocusHandler
 * Signature: (Lorg/cef/handler/CefFocusHandler;)V
 */
JNIEXPORT void JNICALL Java_org_cef_handler_CefClientHandler_N_1removeFocusHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_handler_CefClientHandler
 * Method:    N_removeLifeSpanHandler
 * Signature: (Lorg/cef/handler/CefLifeSpanHandler;)V
 */
JNIEXPORT void JNICALL Java_org_cef_handler_CefClientHandler_N_1removeLifeSpanHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_handler_CefClientHandler
 * Method:    N_removeMessageRouterHandler
 * Signature: (Lorg/cef/handler/CefMessageRouterHandler;)V
 */
JNIEXPORT void JNICALL Java_org_cef_handler_CefClientHandler_N_1removeMessageRouterHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_handler_CefClientHandler
 * Method:    N_removeLoadHandler
 * Signature: (Lorg/cef/handler/CefLoadHandler;)V
 */
JNIEXPORT void JNICALL Java_org_cef_handler_CefClientHandler_N_1removeLoadHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_handler_CefClientHandler
 * Method:    N_removeRenderHandler
 * Signature: (Lorg/cef/handler/CefRenderHandler;)V
 */
JNIEXPORT void JNICALL Java_org_cef_handler_CefClientHandler_N_1removeRenderHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_handler_CefClientHandler
 * Method:    N_CefClientHandler_DTOR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_handler_CefClientHandler_N_1CefClientHandler_1DTOR
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
