/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefDragData_N */

#ifndef _Included_org_cef_callback_CefDragData_N
#define _Included_org_cef_callback_CefDragData_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_IsLink
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDragData_1N_N_1IsLink
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_IsFragment
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDragData_1N_N_1IsFragment
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_IsFile
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDragData_1N_N_1IsFile
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetLinkURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefDragData_1N_N_1GetLinkURL
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetLinkTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefDragData_1N_N_1GetLinkTitle
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetLinkMetadata
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefDragData_1N_N_1GetLinkMetadata
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFragmentText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefDragData_1N_N_1GetFragmentText
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFragmentHtml
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefDragData_1N_N_1GetFragmentHtml
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFragmentBaseURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefDragData_1N_N_1GetFragmentBaseURL
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefDragData_1N_N_1GetFileName
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFileNames
 * Signature: (Ljava/util/Vector;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDragData_1N_N_1GetFileNames
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
