/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_misc_CefPrintSettings_N */

#ifndef _Included_org_cef_misc_CefPrintSettings_N
#define _Included_org_cef_misc_CefPrintSettings_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_CefPrintSettings_CTOR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1CefPrintSettings_1CTOR
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_IsValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1IsValid
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_IsReadOnly
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1IsReadOnly
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_Copy
 * Signature: ()Lorg/cef/misc/CefPrintSettings;
 */
JNIEXPORT jobject JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1Copy
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetOrientation
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetOrientation
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_IsLandscape
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1IsLandscape
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetPrinterPrintableArea
 * Signature: (Ljava/awt/Dimension;Ljava/awt/Rectangle;Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetPrinterPrintableArea
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetDeviceName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetDeviceName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetDeviceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1GetDeviceName
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetDPI
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetDPI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetDPI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1GetDPI
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetPageRanges
 * Signature: (Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetPageRanges
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetPageRangesCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1GetPageRangesCount
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetPageRanges
 * Signature: (Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1GetPageRanges
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetSelectionOnly
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetSelectionOnly
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_IsSelectionOnly
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1IsSelectionOnly
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetCollate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetCollate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_WillCollate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1WillCollate
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetColorModel
 * Signature: (Lorg/cef/misc/CefPrintSettings/ColorModel;)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetColorModel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetColorModel
 * Signature: ()Lorg/cef/misc/CefPrintSettings/ColorModel;
 */
JNIEXPORT jobject JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1GetColorModel
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetCopies
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetCopies
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetCopies
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1GetCopies
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetDuplexMode
 * Signature: (Lorg/cef/misc/CefPrintSettings/DuplexMode;)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetDuplexMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetDuplexMode
 * Signature: ()Lorg/cef/misc/CefPrintSettings/DuplexMode;
 */
JNIEXPORT jobject JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1GetDuplexMode
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_CefPrintSettings_DTOR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1CefPrintSettings_1DTOR
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
