/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_CefApp */

#ifndef _Included_org_cef_CefApp
#define _Included_org_cef_CefApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_CefApp
 * Method:    N_PreInitialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_CefApp_N_1PreInitialize(JNIEnv*,
                                                                jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_Initialize
 * Signature:
 * (Ljava/lang/String;Lorg/cef/handler/CefAppHandler;Lorg/cef/CefSettings;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_CefApp_N_1Initialize(JNIEnv*, jobject, jstring, jobject, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_Shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_CefApp_N_1Shutdown(JNIEnv*, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_DoMessageLoopWork
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_CefApp_N_1DoMessageLoopWork(JNIEnv*,
                                                                jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_GetVersion
 * Signature: ()Lorg/cef/CefApp/CefVersion;
 */
JNIEXPORT jobject JNICALL Java_org_cef_CefApp_N_1GetVersion(JNIEnv*, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_RegisterSchemeHandlerFactory
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Lorg/cef/callback/CefSchemeHandlerFactory;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_CefApp_N_1RegisterSchemeHandlerFactory(JNIEnv*,
                                                    jobject,
                                                    jstring,
                                                    jstring,
                                                    jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_ClearSchemeHandlerFactories
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_CefApp_N_1ClearSchemeHandlerFactories(JNIEnv*, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_Startup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_CefApp_N_1Startup(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_cef_CefApp_CefAppState */

#ifndef _Included_org_cef_CefApp_CefAppState
#define _Included_org_cef_CefApp_CefAppState
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_cef_CefApp_CefVersion */

#ifndef _Included_org_cef_CefApp_CefVersion
#define _Included_org_cef_CefApp_CefVersion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
