/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefAuthCallback_N */

#ifndef _Included_org_cef_callback_CefAuthCallback_N
#define _Included_org_cef_callback_CefAuthCallback_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefAuthCallback_N
 * Method:    N_Continue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefAuthCallback_1N_N_1Continue
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_cef_callback_CefAuthCallback_N
 * Method:    N_Cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefAuthCallback_1N_N_1Cancel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
