/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefBeforeDownloadCallback_N */

#ifndef _Included_org_cef_callback_CefBeforeDownloadCallback_N
#define _Included_org_cef_callback_CefBeforeDownloadCallback_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefBeforeDownloadCallback_N
 * Method:    N_Continue
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefBeforeDownloadCallback_1N_N_1Continue(JNIEnv*,
                                                               jobject,
                                                               jlong,
                                                               jstring,
                                                               jboolean);

#ifdef __cplusplus
}
#endif
#endif
