/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefCallback_N */

#ifndef _Included_org_cef_callback_CefCallback_N
#define _Included_org_cef_callback_CefCallback_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefCallback_N
 * Method:    N_Continue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefCallback_1N_N_1Continue(JNIEnv*,
                                                                        jobject,
                                                                        jlong);

/*
 * Class:     org_cef_callback_CefCallback_N
 * Method:    N_Cancel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefCallback_1N_N_1Cancel(JNIEnv*,
                                                                      jobject,
                                                                      jlong);

#ifdef __cplusplus
}
#endif
#endif
