/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefCommandLine_N */

#ifndef _Included_org_cef_callback_CefCommandLine_N
#define _Included_org_cef_callback_CefCommandLine_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_Reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefCommandLine_1N_N_1Reset(JNIEnv*,
                                                                        jobject,
                                                                        jlong);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_GetProgram
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1GetProgram(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_SetProgram
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1SetProgram(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jstring);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_HasSwitches
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1HasSwitches(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_HasSwitch
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1HasSwitch(JNIEnv*,
                                                     jobject,
                                                     jlong,
                                                     jstring);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_GetSwitchValue
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1GetSwitchValue(JNIEnv*,
                                                          jobject,
                                                          jlong,
                                                          jstring);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_GetSwitches
 * Signature: (J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1GetSwitches(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_AppendSwitch
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1AppendSwitch(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jstring);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_AppendSwitchWithValue
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1AppendSwitchWithValue(JNIEnv*,
                                                                 jobject,
                                                                 jlong,
                                                                 jstring,
                                                                 jstring);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_HasArguments
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1HasArguments(JNIEnv*,
                                                        jobject,
                                                        jlong);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_GetArguments
 * Signature: (J)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1GetArguments(JNIEnv*,
                                                        jobject,
                                                        jlong);

/*
 * Class:     org_cef_callback_CefCommandLine_N
 * Method:    N_AppendArgument
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefCommandLine_1N_N_1AppendArgument(JNIEnv*,
                                                          jobject,
                                                          jlong,
                                                          jstring);

#ifdef __cplusplus
}
#endif
#endif
