/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefContextMenuParams_N */

#ifndef _Included_org_cef_callback_CefContextMenuParams_N
#define _Included_org_cef_callback_CefContextMenuParams_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetXCoord
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetXCoord
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetYCoord
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetYCoord
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetTypeFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetTypeFlags
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetLinkUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetLinkUrl
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetUnfilteredLinkUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetUnfilteredLinkUrl
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetSourceUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetSourceUrl
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_HasImageContents
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1HasImageContents
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetPageUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetPageUrl
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetFrameUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetFrameUrl
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetFrameCharset
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetFrameCharset
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetMediaType
 * Signature: ()Lorg/cef/callback/CefContextMenuParams/MediaType;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetMediaType
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetMediaStateFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetMediaStateFlags
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetSelectionText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetSelectionText
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetMisspelledWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetMisspelledWord
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetDictionarySuggestions
 * Signature: (Ljava/util/Vector;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetDictionarySuggestions
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_IsEditable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1IsEditable
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_IsSpellCheckEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1IsSpellCheckEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetEditStateFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefContextMenuParams_1N_N_1GetEditStateFlags
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
