/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefContextMenuParams_N */

#ifndef _Included_org_cef_callback_CefContextMenuParams_N
#define _Included_org_cef_callback_CefContextMenuParams_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetXCoord
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetXCoord(JNIEnv*,
                                                           jobject,
                                                           jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetYCoord
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetYCoord(JNIEnv*,
                                                           jobject,
                                                           jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetTypeFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetTypeFlags(JNIEnv*,
                                                              jobject,
                                                              jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetLinkUrl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetLinkUrl(JNIEnv*,
                                                            jobject,
                                                            jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetUnfilteredLinkUrl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetUnfilteredLinkUrl(JNIEnv*,
                                                                      jobject,
                                                                      jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetSourceUrl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetSourceUrl(JNIEnv*,
                                                              jobject,
                                                              jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_HasImageContents
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1HasImageContents(JNIEnv*,
                                                                  jobject,
                                                                  jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetPageUrl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetPageUrl(JNIEnv*,
                                                            jobject,
                                                            jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetFrameUrl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetFrameUrl(JNIEnv*,
                                                             jobject,
                                                             jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetFrameCharset
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetFrameCharset(JNIEnv*,
                                                                 jobject,
                                                                 jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetMediaType
 * Signature: (J)Lorg/cef/callback/CefContextMenuParams/MediaType;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetMediaType(JNIEnv*,
                                                              jobject,
                                                              jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetMediaStateFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetMediaStateFlags(JNIEnv*,
                                                                    jobject,
                                                                    jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetSelectionText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetSelectionText(JNIEnv*,
                                                                  jobject,
                                                                  jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetMisspelledWord
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetMisspelledWord(JNIEnv*,
                                                                   jobject,
                                                                   jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetDictionarySuggestions
 * Signature: (JLjava/util/Vector;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetDictionarySuggestions(
    JNIEnv*,
    jobject,
    jlong,
    jobject);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_IsEditable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1IsEditable(JNIEnv*,
                                                            jobject,
                                                            jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_IsSpellCheckEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1IsSpellCheckEnabled(JNIEnv*,
                                                                     jobject,
                                                                     jlong);

/*
 * Class:     org_cef_callback_CefContextMenuParams_N
 * Method:    N_GetEditStateFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefContextMenuParams_1N_N_1GetEditStateFlags(JNIEnv*,
                                                                   jobject,
                                                                   jlong);

#ifdef __cplusplus
}
#endif
#endif
