/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefDragData_N */

#ifndef _Included_org_cef_callback_CefDragData_N
#define _Included_org_cef_callback_CefDragData_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_Create
 * Signature: ()Lorg/cef/callback/CefDragData_N;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefDragData_1N_N_1Create(JNIEnv*, jclass);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_Clone
 * Signature: (J)Lorg/cef/callback/CefDragData_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefDragData_1N_N_1Clone(JNIEnv*,
                                                                        jobject,
                                                                        jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefDragData_1N_N_1Dispose(JNIEnv*,
                                                                       jobject,
                                                                       jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_IsReadOnly
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefDragData_1N_N_1IsReadOnly(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_IsLink
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefDragData_1N_N_1IsLink(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_IsFragment
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefDragData_1N_N_1IsFragment(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_IsFile
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefDragData_1N_N_1IsFile(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetLinkURL
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDragData_1N_N_1GetLinkURL(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetLinkTitle
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDragData_1N_N_1GetLinkTitle(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetLinkMetadata
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDragData_1N_N_1GetLinkMetadata(JNIEnv*,
                                                        jobject,
                                                        jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFragmentText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDragData_1N_N_1GetFragmentText(JNIEnv*,
                                                        jobject,
                                                        jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFragmentHtml
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDragData_1N_N_1GetFragmentHtml(JNIEnv*,
                                                        jobject,
                                                        jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFragmentBaseURL
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDragData_1N_N_1GetFragmentBaseURL(JNIEnv*,
                                                           jobject,
                                                           jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFileContents
 * Signature: (JLjava/io/OutputStream;)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefDragData_1N_N_1GetFileContents(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFileName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDragData_1N_N_1GetFileName(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_GetFileNames
 * Signature: (JLjava/util/Vector;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefDragData_1N_N_1GetFileNames(JNIEnv*,
                                                     jobject,
                                                     jlong,
                                                     jobject);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_SetLinkURL
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefDragData_1N_N_1SetLinkURL(JNIEnv*,
                                                   jobject,
                                                   jlong,
                                                   jstring);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_SetLinkTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefDragData_1N_N_1SetLinkTitle(JNIEnv*,
                                                     jobject,
                                                     jlong,
                                                     jstring);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_SetLinkMetadata
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefDragData_1N_N_1SetLinkMetadata(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jstring);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_SetFragmentText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefDragData_1N_N_1SetFragmentText(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jstring);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_SetFragmentHtml
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefDragData_1N_N_1SetFragmentHtml(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jstring);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_SetFragmentBaseURL
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefDragData_1N_N_1SetFragmentBaseURL(JNIEnv*,
                                                           jobject,
                                                           jlong,
                                                           jstring);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_ResetFileContents
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefDragData_1N_N_1ResetFileContents(JNIEnv*,
                                                          jobject,
                                                          jlong);

/*
 * Class:     org_cef_callback_CefDragData_N
 * Method:    N_AddFile
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefDragData_1N_N_1AddFile(JNIEnv*,
                                                                       jobject,
                                                                       jlong,
                                                                       jstring,
                                                                       jstring);

#ifdef __cplusplus
}
#endif
#endif
