/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefDownloadItem_N */

#ifndef _Included_org_cef_callback_CefDownloadItem_N
#define _Included_org_cef_callback_CefDownloadItem_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_IsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1IsValid(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_IsInProgress
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1IsInProgress(JNIEnv*,
                                                         jobject,
                                                         jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_IsComplete
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1IsComplete(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_IsCanceled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1IsCanceled(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetCurrentSpeed
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetCurrentSpeed(JNIEnv*,
                                                            jobject,
                                                            jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetPercentComplete
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetPercentComplete(JNIEnv*,
                                                               jobject,
                                                               jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetTotalBytes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetTotalBytes(JNIEnv*,
                                                          jobject,
                                                          jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetReceivedBytes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetReceivedBytes(JNIEnv*,
                                                             jobject,
                                                             jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetStartTime
 * Signature: (J)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetStartTime(JNIEnv*,
                                                         jobject,
                                                         jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetEndTime
 * Signature: (J)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetEndTime(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetFullPath
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetFullPath(JNIEnv*,
                                                        jobject,
                                                        jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetId(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetURL
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetURL(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetSuggestedFileName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetSuggestedFileName(JNIEnv*,
                                                                 jobject,
                                                                 jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetContentDisposition
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetContentDisposition(JNIEnv*,
                                                                  jobject,
                                                                  jlong);

/*
 * Class:     org_cef_callback_CefDownloadItem_N
 * Method:    N_GetMimeType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefDownloadItem_1N_N_1GetMimeType(JNIEnv*,
                                                        jobject,
                                                        jlong);

#ifdef __cplusplus
}
#endif
#endif
