/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_browser_CefFrame_N */

#ifndef _Included_org_cef_browser_CefFrame_N
#define _Included_org_cef_browser_CefFrame_N
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_cef_browser_CefFrame_N
 * Method:    N_CefFrame_1DTOR
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_org_cef_browser_CefFrame_1N_N_1CefFrame_1DTOR(JNIEnv*, jobject);

/*
 * Class:     org_cef_browser_CefFrame_N
 * Method:    N_GetIdentifier
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL
Java_org_cef_browser_CefFrame_1N_N_1GetIdentifier(JNIEnv*, jobject);

/*
 * Class:     org_cef_browser_CefFrame_N
 * Method:    N_GetURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_browser_CefFrame_1N_N_1GetURL(JNIEnv*,
                                                                     jobject);

/*
 * Class:     org_cef_browser_CefFrame_N
 * Method:    N_GetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_browser_CefFrame_1N_N_1GetName(JNIEnv*,
                                                                      jobject);

/*
 * Class:     org_cef_browser_CefFrame_N
 * Method:    N_IsMain
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefFrame_1N_N_1IsMain(JNIEnv*,
                                                                      jobject);

/*
 * Class:     org_cef_browser_CefFrame_N
 * Method:    N_IsValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefFrame_1N_N_1IsValid(JNIEnv*,
                                                                       jobject);

/*
 * Class:     org_cef_browser_CefFrame_N
 * Method:    N_IsFocused
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_browser_CefFrame_1N_N_1IsFocused(JNIEnv*, jobject);

/*
 * Class:     org_cef_browser_CefFrame_N
 * Method:    N_GetParent
 * Signature: (Lorg/cef/browser/CefFrame_N;)Z
 */
JNIEXPORT jobject JNICALL
Java_org_cef_browser_CefFrame_1N_N_1GetParent(JNIEnv*, jobject);

/*
 * Class:     org_cef_browser_CefFrame_N
 * Method:    N_ExecuteJavaScript
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL
Java_org_cef_browser_CefFrame_1N_N_1ExecuteJavaScript(JNIEnv* env,
                                                      jobject obj,
                                                      jstring code,
                                                      jstring url,
                                                      jint line);

#ifdef __cplusplus
}
#endif
#endif
