/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefJSDialogCallback_N */

#ifndef _Included_org_cef_callback_CefJSDialogCallback_N
#define _Included_org_cef_callback_CefJSDialogCallback_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefJSDialogCallback_N
 * Method:    N_Continue
 * Signature: (JZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefJSDialogCallback_1N_N_1Continue(JNIEnv*,
                                                         jobject,
                                                         jlong,
                                                         jboolean,
                                                         jstring);

#ifdef __cplusplus
}
#endif
#endif
