/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefMenuModel_N */

#ifndef _Included_org_cef_callback_CefMenuModel_N
#define _Included_org_cef_callback_CefMenuModel_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_Clear
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1Clear
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetCount
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_AddSeparator
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1AddSeparator
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_AddItem
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1AddItem
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_AddCheckItem
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1AddCheckItem
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_AddRadioItem
 * Signature: (ILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1AddRadioItem
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_AddSubMenu
 * Signature: (ILjava/lang/String;)Lorg/cef/callback/CefMenuModel;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1AddSubMenu
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_InsertSeparatorAt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1InsertSeparatorAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_InsertItemAt
 * Signature: (IILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1InsertItemAt
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_InsertCheckItemAt
 * Signature: (IILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1InsertCheckItemAt
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_InsertRadioItemAt
 * Signature: (IILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1InsertRadioItemAt
  (JNIEnv *, jobject, jint, jint, jstring, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_InsertSubMenuAt
 * Signature: (IILjava/lang/String;)Lorg/cef/callback/CefMenuModel;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1InsertSubMenuAt
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_Remove
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1Remove
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_RemoveAt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1RemoveAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetIndexOf
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetIndexOf
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetCommandIdAt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetCommandIdAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetCommandIdAt
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetCommandIdAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetLabel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetLabel
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetLabelAt
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetLabelAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetLabel
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetLabel
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetLabelAt
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetLabelAt
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetType
 * Signature: (I)Lorg/cef/callback/CefMenuModel/MenuItemType;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetType
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetTypeAt
 * Signature: (I)Lorg/cef/callback/CefMenuModel/MenuItemType;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetTypeAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetGroupId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetGroupId
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetGroupIdAt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetGroupIdAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetGroupId
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetGroupId
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetGroupIdAt
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetGroupIdAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetSubMenu
 * Signature: (I)Lorg/cef/callback/CefMenuModel;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetSubMenu
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetSubMenuAt
 * Signature: (I)Lorg/cef/callback/CefMenuModel;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetSubMenuAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsVisible
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1IsVisible
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsVisibleAt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1IsVisibleAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetVisible
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetVisible
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetVisibleAt
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetVisibleAt
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1IsEnabled
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsEnabledAt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1IsEnabledAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetEnabled
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetEnabled
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetEnabledAt
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetEnabledAt
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsChecked
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1IsChecked
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsCheckedAt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1IsCheckedAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetChecked
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetChecked
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetCheckedAt
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetCheckedAt
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_HasAccelerator
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1HasAccelerator
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_HasAcceleratorAt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1HasAcceleratorAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetAccelerator
 * Signature: (IIZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetAccelerator
  (JNIEnv *, jobject, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetAcceleratorAt
 * Signature: (IIZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1SetAcceleratorAt
  (JNIEnv *, jobject, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_RemoveAccelerator
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1RemoveAccelerator
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_RemoveAcceleratorAt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1RemoveAcceleratorAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetAccelerator
 * Signature: (ILorg/cef/misc/IntRef;Lorg/cef/misc/BoolRef;Lorg/cef/misc/BoolRef;Lorg/cef/misc/BoolRef;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetAccelerator
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetAcceleratorAt
 * Signature: (ILorg/cef/misc/IntRef;Lorg/cef/misc/BoolRef;Lorg/cef/misc/BoolRef;Lorg/cef/misc/BoolRef;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefMenuModel_1N_N_1GetAcceleratorAt
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
