/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefMenuModel_N */

#ifndef _Included_org_cef_callback_CefMenuModel_N
#define _Included_org_cef_callback_CefMenuModel_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_Clear
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1Clear(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetCount(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_AddSeparator
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1AddSeparator(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_AddItem
 * Signature: (JILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1AddItem(JNIEnv*,
                                                 jobject,
                                                 jlong,
                                                 jint,
                                                 jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_AddCheckItem
 * Signature: (JILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1AddCheckItem(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jint,
                                                      jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_AddRadioItem
 * Signature: (JILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1AddRadioItem(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jint,
                                                      jstring,
                                                      jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_AddSubMenu
 * Signature: (JILjava/lang/String;)Lorg/cef/callback/CefMenuModel;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1AddSubMenu(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jint,
                                                    jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_InsertSeparatorAt
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1InsertSeparatorAt(JNIEnv*,
                                                           jobject,
                                                           jlong,
                                                           jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_InsertItemAt
 * Signature: (JIILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1InsertItemAt(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jint,
                                                      jint,
                                                      jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_InsertCheckItemAt
 * Signature: (JIILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1InsertCheckItemAt(JNIEnv*,
                                                           jobject,
                                                           jlong,
                                                           jint,
                                                           jint,
                                                           jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_InsertRadioItemAt
 * Signature: (JIILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1InsertRadioItemAt(JNIEnv*,
                                                           jobject,
                                                           jlong,
                                                           jint,
                                                           jint,
                                                           jstring,
                                                           jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_InsertSubMenuAt
 * Signature: (JIILjava/lang/String;)Lorg/cef/callback/CefMenuModel;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1InsertSubMenuAt(JNIEnv*,
                                                         jobject,
                                                         jlong,
                                                         jint,
                                                         jint,
                                                         jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_Remove
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1Remove(JNIEnv*, jobject, jlong, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_RemoveAt
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1RemoveAt(JNIEnv*,
                                                  jobject,
                                                  jlong,
                                                  jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetIndexOf
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetIndexOf(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetCommandIdAt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetCommandIdAt(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetCommandIdAt
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetCommandIdAt(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jint,
                                                        jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetLabel
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetLabel(JNIEnv*,
                                                  jobject,
                                                  jlong,
                                                  jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetLabelAt
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetLabelAt(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetLabel
 * Signature: (JILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetLabel(JNIEnv*,
                                                  jobject,
                                                  jlong,
                                                  jint,
                                                  jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetLabelAt
 * Signature: (JILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetLabelAt(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jint,
                                                    jstring);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetType
 * Signature: (JI)Lorg/cef/callback/CefMenuModel/MenuItemType;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetType(JNIEnv*, jobject, jlong, jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetTypeAt
 * Signature: (JI)Lorg/cef/callback/CefMenuModel/MenuItemType;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetTypeAt(JNIEnv*,
                                                   jobject,
                                                   jlong,
                                                   jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetGroupId
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetGroupId(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetGroupIdAt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetGroupIdAt(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetGroupId
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetGroupId(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jint,
                                                    jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetGroupIdAt
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetGroupIdAt(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jint,
                                                      jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetSubMenu
 * Signature: (JI)Lorg/cef/callback/CefMenuModel;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetSubMenu(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetSubMenuAt
 * Signature: (JI)Lorg/cef/callback/CefMenuModel;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetSubMenuAt(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsVisible
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1IsVisible(JNIEnv*,
                                                   jobject,
                                                   jlong,
                                                   jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsVisibleAt
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1IsVisibleAt(JNIEnv*,
                                                     jobject,
                                                     jlong,
                                                     jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetVisible
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetVisible(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jint,
                                                    jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetVisibleAt
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetVisibleAt(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jint,
                                                      jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsEnabled
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1IsEnabled(JNIEnv*,
                                                   jobject,
                                                   jlong,
                                                   jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsEnabledAt
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1IsEnabledAt(JNIEnv*,
                                                     jobject,
                                                     jlong,
                                                     jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetEnabled
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetEnabled(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jint,
                                                    jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetEnabledAt
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetEnabledAt(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jint,
                                                      jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsChecked
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1IsChecked(JNIEnv*,
                                                   jobject,
                                                   jlong,
                                                   jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_IsCheckedAt
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1IsCheckedAt(JNIEnv*,
                                                     jobject,
                                                     jlong,
                                                     jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetChecked
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetChecked(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jint,
                                                    jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetCheckedAt
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetCheckedAt(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jint,
                                                      jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_HasAccelerator
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1HasAccelerator(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_HasAcceleratorAt
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1HasAcceleratorAt(JNIEnv*,
                                                          jobject,
                                                          jlong,
                                                          jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetAccelerator
 * Signature: (JIIZZZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetAccelerator(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jint,
                                                        jint,
                                                        jboolean,
                                                        jboolean,
                                                        jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_SetAcceleratorAt
 * Signature: (JIIZZZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1SetAcceleratorAt(JNIEnv*,
                                                          jobject,
                                                          jlong,
                                                          jint,
                                                          jint,
                                                          jboolean,
                                                          jboolean,
                                                          jboolean);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_RemoveAccelerator
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1RemoveAccelerator(JNIEnv*,
                                                           jobject,
                                                           jlong,
                                                           jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_RemoveAcceleratorAt
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1RemoveAcceleratorAt(JNIEnv*,
                                                             jobject,
                                                             jlong,
                                                             jint);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetAccelerator
 * Signature:
 * (JILorg/cef/misc/IntRef;Lorg/cef/misc/BoolRef;Lorg/cef/misc/BoolRef;Lorg/cef/misc/BoolRef;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetAccelerator(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jint,
                                                        jobject,
                                                        jobject,
                                                        jobject,
                                                        jobject);

/*
 * Class:     org_cef_callback_CefMenuModel_N
 * Method:    N_GetAcceleratorAt
 * Signature:
 * (JILorg/cef/misc/IntRef;Lorg/cef/misc/BoolRef;Lorg/cef/misc/BoolRef;Lorg/cef/misc/BoolRef;)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefMenuModel_1N_N_1GetAcceleratorAt(JNIEnv*,
                                                          jobject,
                                                          jlong,
                                                          jint,
                                                          jobject,
                                                          jobject,
                                                          jobject,
                                                          jobject);

#ifdef __cplusplus
}
#endif
#endif
