/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_network_CefPostData_N */

#ifndef _Included_org_cef_network_CefPostData_N
#define _Included_org_cef_network_CefPostData_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_network_CefPostData_N
 * Method:    N_CefPostData_CTOR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_network_CefPostData_1N_N_1CefPostData_1CTOR
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_network_CefPostData_N
 * Method:    N_IsReadOnly
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_network_CefPostData_1N_N_1IsReadOnly
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_network_CefPostData_N
 * Method:    N_GetElementCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_network_CefPostData_1N_N_1GetElementCount
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_network_CefPostData_N
 * Method:    N_GetElements
 * Signature: (Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_org_cef_network_CefPostData_1N_N_1GetElements
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_network_CefPostData_N
 * Method:    N_RemoveElement
 * Signature: (Lorg/cef/network/CefPostDataElement;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_network_CefPostData_1N_N_1RemoveElement
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_network_CefPostData_N
 * Method:    N_AddElement
 * Signature: (Lorg/cef/network/CefPostDataElement;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_network_CefPostData_1N_N_1AddElement
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_network_CefPostData_N
 * Method:    N_RemoveElements
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_network_CefPostData_1N_N_1RemoveElements
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_network_CefPostData_N
 * Method:    N_CefPostData_DTOR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_network_CefPostData_1N_N_1CefPostData_1DTOR
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
