/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_misc_CefPrintSettings_N */

#ifndef _Included_org_cef_misc_CefPrintSettings_N
#define _Included_org_cef_misc_CefPrintSettings_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_Create
 * Signature: ()Lorg/cef/misc/CefPrintSettings_N;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1Create(JNIEnv*, jclass);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1Dispose(JNIEnv*,
                                                                        jobject,
                                                                        jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_IsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1IsValid(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_IsReadOnly
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1IsReadOnly(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetOrientation
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1SetOrientation(JNIEnv*,
                                                        jobject,
                                                        jlong,
                                                        jboolean);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_IsLandscape
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1IsLandscape(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetPrinterPrintableArea
 * Signature: (JLjava/awt/Dimension;Ljava/awt/Rectangle;Z)V
 */
JNIEXPORT void JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1SetPrinterPrintableArea(JNIEnv*,
                                                                 jobject,
                                                                 jlong,
                                                                 jobject,
                                                                 jobject,
                                                                 jboolean);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetDeviceName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1SetDeviceName(JNIEnv*,
                                                       jobject,
                                                       jlong,
                                                       jstring);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetDeviceName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1GetDeviceName(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetDPI
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1SetDPI(JNIEnv*,
                                                                       jobject,
                                                                       jlong,
                                                                       jint);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetDPI
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_cef_misc_CefPrintSettings_1N_N_1GetDPI(JNIEnv*,
                                                                       jobject,
                                                                       jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetPageRanges
 * Signature: (JLjava/util/Vector;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1SetPageRanges(JNIEnv*,
                                                       jobject,
                                                       jlong,
                                                       jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetPageRangesCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1GetPageRangesCount(JNIEnv*,
                                                            jobject,
                                                            jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetPageRanges
 * Signature: (JLjava/util/Vector;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1GetPageRanges(JNIEnv*,
                                                       jobject,
                                                       jlong,
                                                       jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetSelectionOnly
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1SetSelectionOnly(JNIEnv*,
                                                          jobject,
                                                          jlong,
                                                          jboolean);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_IsSelectionOnly
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1IsSelectionOnly(JNIEnv*,
                                                         jobject,
                                                         jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetCollate
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1SetCollate(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jboolean);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_WillCollate
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1WillCollate(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetColorModel
 * Signature: (JLorg/cef/misc/CefPrintSettings/ColorModel;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1SetColorModel(JNIEnv*,
                                                       jobject,
                                                       jlong,
                                                       jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetColorModel
 * Signature: (J)Lorg/cef/misc/CefPrintSettings/ColorModel;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1GetColorModel(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetCopies
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1SetCopies(JNIEnv*,
                                                   jobject,
                                                   jlong,
                                                   jint);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetCopies
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1GetCopies(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_SetDuplexMode
 * Signature: (JLorg/cef/misc/CefPrintSettings/DuplexMode;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1SetDuplexMode(JNIEnv*,
                                                       jobject,
                                                       jlong,
                                                       jobject);

/*
 * Class:     org_cef_misc_CefPrintSettings_N
 * Method:    N_GetDuplexMode
 * Signature: (J)Lorg/cef/misc/CefPrintSettings/DuplexMode;
 */
JNIEXPORT jobject JNICALL
Java_org_cef_misc_CefPrintSettings_1N_N_1GetDuplexMode(JNIEnv*, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
