/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefQueryCallback_N */

#ifndef _Included_org_cef_callback_CefQueryCallback_N
#define _Included_org_cef_callback_CefQueryCallback_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefQueryCallback_N
 * Method:    N_Success
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefQueryCallback_1N_N_1Success(JNIEnv*,
                                                     jobject,
                                                     jlong,
                                                     jstring);

/*
 * Class:     org_cef_callback_CefQueryCallback_N
 * Method:    N_Failure
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_cef_callback_CefQueryCallback_1N_N_1Failure(JNIEnv*,
                                                     jobject,
                                                     jlong,
                                                     jint,
                                                     jstring);

#ifdef __cplusplus
}
#endif
#endif
