/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_browser_CefRegistration_N */

#ifndef _Included_org_cef_browser_CefRegistration_N
#define _Included_org_cef_browser_CefRegistration_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_browser_CefRegistration_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_org_cef_browser_CefRegistration_1N_N_1Dispose(JNIEnv*, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
