/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefSchemeRegistrar_N */

#ifndef _Included_org_cef_callback_CefSchemeRegistrar_N
#define _Included_org_cef_callback_CefSchemeRegistrar_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefSchemeRegistrar_N
 * Method:    N_AddCustomScheme
 * Signature: (Ljava/lang/String;ZZZZZZZ)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_cef_callback_CefSchemeRegistrar_1N_N_1AddCustomScheme(JNIEnv*,
                                                               jobject,
                                                               jstring,
                                                               jboolean,
                                                               jboolean,
                                                               jboolean,
                                                               jboolean,
                                                               jboolean,
                                                               jboolean,
                                                               jboolean);

#ifdef __cplusplus
}
#endif
#endif
