/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_network_CefURLRequest_N */

#ifndef _Included_org_cef_network_CefURLRequest_N
#define _Included_org_cef_network_CefURLRequest_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_network_CefURLRequest_N
 * Method:    N_CefURLRequest_CTOR
 * Signature: (Lorg/cef/network/CefRequest;Lorg/cef/callback/CefURLRequestClient;)V
 */
JNIEXPORT void JNICALL Java_org_cef_network_CefURLRequest_1N_N_1CefURLRequest_1CTOR
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_cef_network_CefURLRequest_N
 * Method:    N_GetRequestStatus
 * Signature: ()Lorg/cef/network/CefURLRequest/Status;
 */
JNIEXPORT jobject JNICALL Java_org_cef_network_CefURLRequest_1N_N_1GetRequestStatus
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_network_CefURLRequest_N
 * Method:    N_GetRequestError
 * Signature: ()Lorg/cef/handler/CefLoadHandler/ErrorCode;
 */
JNIEXPORT jobject JNICALL Java_org_cef_network_CefURLRequest_1N_N_1GetRequestError
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_network_CefURLRequest_N
 * Method:    N_GetResponse
 * Signature: ()Lorg/cef/network/CefResponse;
 */
JNIEXPORT jobject JNICALL Java_org_cef_network_CefURLRequest_1N_N_1GetResponse
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_network_CefURLRequest_N
 * Method:    N_Cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_network_CefURLRequest_1N_N_1Cancel
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_network_CefURLRequest_N
 * Method:    N_CefURLRequest_DTOR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_network_CefURLRequest_1N_N_1CefURLRequest_1DTOR
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
