/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_network_CefWebPluginInfo_N */

#ifndef _Included_org_cef_network_CefWebPluginInfo_N
#define _Included_org_cef_network_CefWebPluginInfo_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_network_CefWebPluginInfo_N
 * Method:    N_GetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_network_CefWebPluginInfo_1N_N_1GetName(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_network_CefWebPluginInfo_N
 * Method:    N_GetPath
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_network_CefWebPluginInfo_1N_N_1GetPath(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_network_CefWebPluginInfo_N
 * Method:    N_GetVersion
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_network_CefWebPluginInfo_1N_N_1GetVersion(JNIEnv*, jobject, jlong);

/*
 * Class:     org_cef_network_CefWebPluginInfo_N
 * Method:    N_GetDescription
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_cef_network_CefWebPluginInfo_1N_N_1GetDescription(JNIEnv*,
                                                           jobject,
                                                           jlong);

#ifdef __cplusplus
}
#endif
#endif
