// Copyright (c) 2010 Lime Wire, LLC. All rights reserved. Use of this source
// code is governed by a BSD-style license that can be found in the LICENSE file.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_limewire_cef_CefBrowser_N */

#ifndef _Included_org_limewire_cef_CefBrowser_N
#define _Included_org_limewire_cef_CefBrowser_N
#ifdef __cplusplus
extern "C" {
#endif
#undef org_limewire_cef_CefBrowser_N_FOCUS_TRAVERSABLE_UNKNOWN
#define org_limewire_cef_CefBrowser_N_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef org_limewire_cef_CefBrowser_N_FOCUS_TRAVERSABLE_DEFAULT
#define org_limewire_cef_CefBrowser_N_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef org_limewire_cef_CefBrowser_N_FOCUS_TRAVERSABLE_SET
#define org_limewire_cef_CefBrowser_N_FOCUS_TRAVERSABLE_SET 2L
#undef org_limewire_cef_CefBrowser_N_TOP_ALIGNMENT
#define org_limewire_cef_CefBrowser_N_TOP_ALIGNMENT 0.0f
#undef org_limewire_cef_CefBrowser_N_CENTER_ALIGNMENT
#define org_limewire_cef_CefBrowser_N_CENTER_ALIGNMENT 0.5f
#undef org_limewire_cef_CefBrowser_N_BOTTOM_ALIGNMENT
#define org_limewire_cef_CefBrowser_N_BOTTOM_ALIGNMENT 1.0f
#undef org_limewire_cef_CefBrowser_N_LEFT_ALIGNMENT
#define org_limewire_cef_CefBrowser_N_LEFT_ALIGNMENT 0.0f
#undef org_limewire_cef_CefBrowser_N_RIGHT_ALIGNMENT
#define org_limewire_cef_CefBrowser_N_RIGHT_ALIGNMENT 1.0f
#undef org_limewire_cef_CefBrowser_N_serialVersionUID
#define org_limewire_cef_CefBrowser_N_serialVersionUID -7644114512714619750i64
#undef org_limewire_cef_CefBrowser_N_serialVersionUID
#define org_limewire_cef_CefBrowser_N_serialVersionUID -2284879212465893870i64
/*
 * Class:     org_limewire_cef_CefBrowser_N
 * Method:    N_Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_limewire_cef_CefBrowser_1N_N_1Destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_limewire_cef_CefBrowser_N
 * Method:    N_GoBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_limewire_cef_CefBrowser_1N_N_1GoBack
  (JNIEnv *, jobject);

/*
 * Class:     org_limewire_cef_CefBrowser_N
 * Method:    N_GoForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_limewire_cef_CefBrowser_1N_N_1GoForward
  (JNIEnv *, jobject);

/*
 * Class:     org_limewire_cef_CefBrowser_N
 * Method:    N_GetWindowHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_limewire_cef_CefBrowser_1N_N_1GetWindowHandle
  (JNIEnv *, jobject);

/*
 * Class:     org_limewire_cef_CefBrowser_N
 * Method:    N_IsPopup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_limewire_cef_CefBrowser_1N_N_1IsPopup
  (JNIEnv *, jobject);

/*
 * Class:     org_limewire_cef_CefBrowser_N
 * Method:    N_GetMainFrame
 * Signature: ()Lorg/limewire/cef/CefFrame;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefBrowser_1N_N_1GetMainFrame
  (JNIEnv *, jobject);

/*
 * Class:     org_limewire_cef_CefBrowser_N
 * Method:    N_GetFocusedFrame
 * Signature: ()Lorg/limewire/cef/CefFrame;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefBrowser_1N_N_1GetFocusedFrame
  (JNIEnv *, jobject);

/*
 * Class:     org_limewire_cef_CefBrowser_N
 * Method:    N_Paint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_limewire_cef_CefBrowser_1N_N_1Paint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_limewire_cef_CefBrowser_N
 * Method:    N_SetWindowSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_limewire_cef_CefBrowser_1N_N_1SetWindowSize
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
