// Copyright (c) 2010 Lime Wire, LLC. All rights reserved. Use of this source
// code is governed by a BSD-style license that can be found in the LICENSE file.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_limewire_cef_CefContext */

#ifndef _Included_org_limewire_cef_CefContext
#define _Included_org_limewire_cef_CefContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_Initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_limewire_cef_CefContext_N_1Initialize
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_Shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_limewire_cef_CefContext_N_1Shutdown
  (JNIEnv *, jclass);

/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_CreateV8Undefined
 * Signature: ()Lorg/limewire/cef/CefV8Value;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefContext_N_1CreateV8Undefined
  (JNIEnv *, jclass);

/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_CreateV8Null
 * Signature: ()Lorg/limewire/cef/CefV8Value;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefContext_N_1CreateV8Null
  (JNIEnv *, jclass);

/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_CreateV8Bool
 * Signature: (Z)Lorg/limewire/cef/CefV8Value;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefContext_N_1CreateV8Bool
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_CreateV8Int
 * Signature: (I)Lorg/limewire/cef/CefV8Value;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefContext_N_1CreateV8Int
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_CreateV8Double
 * Signature: (D)Lorg/limewire/cef/CefV8Value;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefContext_N_1CreateV8Double
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_CreateV8String
 * Signature: (Ljava/lang/String;)Lorg/limewire/cef/CefV8Value;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefContext_N_1CreateV8String
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_CreateV8Object
 * Signature: (Ljava/lang/Object;)Lorg/limewire/cef/CefV8Value;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefContext_N_1CreateV8Object
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_CreateV8Array
 * Signature: ()Lorg/limewire/cef/CefV8Value;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefContext_N_1CreateV8Array
  (JNIEnv *, jclass);

/*
 * Class:     org_limewire_cef_CefContext
 * Method:    N_CreateV8Function
 * Signature: (Ljava/lang/String;Lorg/limewire/cef/CefV8Handler;)Lorg/limewire/cef/CefV8Value;
 */
JNIEXPORT jobject JNICALL Java_org_limewire_cef_CefContext_N_1CreateV8Function
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
