// Copyright (c) 2010 Lime Wire, LLC. All rights reserved. Use of this source
// code is governed by a BSD-style license that can be found in the LICENSE file.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_limewire_cef_CefFrame_N */

#ifndef _Included_org_limewire_cef_CefFrame_N
#define _Included_org_limewire_cef_CefFrame_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_limewire_cef_CefFrame_N
 * Method:    N_Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_limewire_cef_CefFrame_1N_N_1Destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_limewire_cef_CefFrame_N
 * Method:    N_LoadURL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_limewire_cef_CefFrame_1N_N_1LoadURL
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_limewire_cef_CefFrame_N
 * Method:    N_ExecuteJavaScript
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_limewire_cef_CefFrame_1N_N_1ExecuteJavaScript
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     org_limewire_cef_CefFrame_N
 * Method:    N_IsMain
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_limewire_cef_CefFrame_1N_N_1IsMain
  (JNIEnv *, jobject);

/*
 * Class:     org_limewire_cef_CefFrame_N
 * Method:    N_IsFocused
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_limewire_cef_CefFrame_1N_N_1IsFocused
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
